export const masterData = {
  constituencies: [
    {id: 1, name: 'Gummidipoondi', dt: 'Thiruvallur'},
    {id: 2, name: 'Ponneri', dt: 'Thiruvallur'},
    {id: 3, name: 'Tiruttani', dt: 'Thiruvallur'},
    {id: 4, name: 'Thiruvallur', dt: 'Thiruvallur'},
    {id: 5, name: 'Poonamallee', dt: 'Thiruvallur'},
    {id: 6, name: 'Avadi', dt: 'Thiruvallur'},
    {id: 7, name: 'Maduravoyal', dt: 'Thiruvallur'},
    {id: 8, name: 'Ambattur', dt: 'Thiruvallur'},
    {id: 9, name: 'Madhavaram', dt: 'Thiruvallur'},
    {id: 10, name: 'Thiruvottiyur', dt: 'Thiruvallur'},
    {id: 11, name: 'Dr. Radhakrishnan Nagar', dt: 'Chennai'},
    {id: 12, name: 'Perambur', dt: 'Chennai'},
    {id: 13, name: 'Kolathur', dt: 'Chennai'},
    {id: 14, name: 'Villivakkam', dt: 'Chennai'},
    {id: 15, name: 'Thiru. Vi. Ka. Nagar', dt: 'Chennai'},
    {id: 16, name: 'Egmore', dt: 'Chennai'},
    {id: 17, name: 'Royapuram', dt: 'Chennai'},
    {id: 18, name: 'Harbour', dt: 'Chennai'},
    {id: 19, name: 'Chepauk-Thiruvallikeni', dt: 'Chennai'},
    {id: 20, name: 'Thousand Lights', dt: 'Chennai'},
    {id: 21, name: 'Anna Nagar', dt: 'Chennai'},
    {id: 22, name: 'Virugambakkam', dt: 'Chennai'},
    {id: 23, name: 'Saidapet', dt: 'Chennai'},
    {id: 24, name: 'T. Nagar', dt: 'Chennai'},
    {id: 25, name: 'Mylapore', dt: 'Chennai'},
    {id: 26, name: 'Velachery', dt: 'Chennai'},
    {id: 27, name: 'Sholinganallur', dt: 'Chengalpattu'},
    {id: 28, name: 'Alandur', dt: 'Kanchipuram'},
    {id: 29, name: 'Sriperumbudur', dt: 'Kanchipuram'},
    {id: 30, name: 'Pallavaram', dt: 'Chengalpattu'},
    {id: 31, name: 'Tambaram', dt: 'Chengalpattu'},
    {id: 32, name: 'Chengalpattu', dt: 'Chengalpattu'},
    {id: 33, name: 'Thiruporur', dt: 'Chengalpattu'},
    {id: 34, name: 'Cheyyur', dt: 'Chengalpattu'},
    {id: 35, name: 'Maduranthakam', dt: 'Chengalpattu'},
    {id: 36, name: 'Uthiramerur', dt: 'Kanchipuram'},
    {id: 37, name: 'Kancheepuram', dt: 'Kanchipuram'},
    {id: 38, name: 'Arakkonam', dt: 'Ranipet'},
    {id: 39, name: 'Sholingur', dt: 'Ranipet'},
    {id: 40, name: 'Katpadi', dt: 'Vellore'},
    {id: 41, name: 'Ranipet', dt: 'Ranipet'},
    {id: 42, name: 'Arcot', dt: 'Ranipet'},
    {id: 43, name: 'Vellore', dt: 'Vellore'},
    {id: 44, name: 'Anaikattu', dt: 'Vellore'},
    {id: 45, name: 'K. V. Kuppam', dt: 'Vellore'},
    {id: 46, name: 'Gudiyattam', dt: 'Vellore'},
    {id: 47, name: 'Vaniyambadi', dt: 'Tirupattur'},
    {id: 48, name: 'Ambur', dt: 'Tirupattur'},
    {id: 49, name: 'Jolarpet', dt: 'Tirupattur'},
    {id: 50, name: 'Tirupattur', dt: 'Tirupattur'},
    {id: 51, name: 'Uthangarai', dt: 'Krishnagiri'},
    {id: 52, name: 'Bargur', dt: 'Krishnagiri'},
    {id: 53, name: 'Krishnagiri', dt: 'Krishnagiri'},
    {id: 54, name: 'Veppanahalli', dt: 'Krishnagiri'},
    {id: 55, name: 'Hosur', dt: 'Krishnagiri'},
    {id: 56, name: 'Thalli', dt: 'Krishnagiri'},
    {id: 57, name: 'Palacode', dt: 'Dharmapuri'},
    {id: 58, name: 'Pennagaram', dt: 'Dharmapuri'},
    {id: 59, name: 'Dharmapuri', dt: 'Dharmapuri'},
    {id: 60, name: 'Pappireddippatti', dt: 'Dharmapuri'},
    {id: 61, name: 'Harur', dt: 'Dharmapuri'},
    {id: 62, name: 'Chengam', dt: 'Tiruvannamalai'},
    {id: 63, name: 'Tiruvannamalai', dt: 'Tiruvannamalai'},
    {id: 64, name: 'Kilpennathur', dt: 'Tiruvannamalai'},
    {id: 65, name: 'Kalasapakkam', dt: 'Tiruvannamalai'},
    {id: 66, name: 'Polur', dt: 'Tiruvannamalai'},
    {id: 67, name: 'Arani', dt: 'Tiruvannamalai'},
    {id: 68, name: 'Cheyyar', dt: 'Tiruvannamalai'},
    {id: 69, name: 'Vandavasi', dt: 'Tiruvannamalai'},
    {id: 70, name: 'Gingee', dt: 'Villupuram'},
    {id: 71, name: 'Mailam', dt: 'Villupuram'},
    {id: 72, name: 'Tindivanam', dt: 'Villupuram'},
    {id: 73, name: 'Vanur', dt: 'Villupuram'},
    {id: 74, name: 'Villupuram', dt: 'Villupuram'},
    {id: 75, name: 'Vikravandi', dt: 'Villupuram'},
    {id: 76, name: 'Tirukkoyilur', dt: 'Kallakurichi'},
    {id: 77, name: 'Ulundurpettai', dt: 'Kallakurichi'},
    {id: 78, name: 'Rishivandiyam', dt: 'Kallakurichi'},
    {id: 79, name: 'Sankarapuram', dt: 'Kallakurichi'},
    {id: 80, name: 'Kallakurichi', dt: 'Kallakurichi'},
    {id: 81, name: 'Gangavalli', dt: 'Salem'},
    {id: 82, name: 'Attur', dt: 'Salem'},
    {id: 83, name: 'Yercaud', dt: 'Salem'},
    {id: 84, name: 'Omalur', dt: 'Salem'},
    {id: 85, name: 'Mettur', dt: 'Salem'},
    {id: 86, name: 'Edapadi', dt: 'Salem'},
    {id: 87, name: 'Sankari', dt: 'Salem'},
    {id: 88, name: 'Salem (West)', dt: 'Salem'},
    {id: 89, name: 'Salem (North)', dt: 'Salem'},
    {id: 90, name: 'Salem (South)', dt: 'Salem'},
    {id: 91, name: 'Veerapandi', dt: 'Salem'},
    {id: 92, name: 'Rasipuram', dt: 'Namakkal'},
    {id: 93, name: 'Senthamangalam', dt: 'Namakkal'},
    {id: 94, name: 'Namakkal', dt: 'Namakkal'},
    {id: 95, name: 'Paramathi Velur', dt: 'Namakkal'},
    {id: 96, name: 'Tiruchengodu', dt: 'Namakkal'},
    {id: 97, name: 'Kumarapalayam', dt: 'Namakkal'},
    {id: 98, name: 'Erode (East)', dt: 'Erode'},
    {id: 99, name: 'Erode (West)', dt: 'Erode'},
    {id: 100, name: 'Modakkurichi', dt: 'Erode'},
    {id: 101, name: 'Dharapuram', dt: 'Tiruppur'},
    {id: 102, name: 'Kangayam', dt: 'Tiruppur'},
    {id: 103, name: 'Perundurai', dt: 'Erode'},
    {id: 104, name: 'Bhavani', dt: 'Erode'},
    {id: 105, name: 'Anthiyur', dt: 'Erode'},
    {id: 106, name: 'Gobichettipalayam', dt: 'Erode'},
    {id: 107, name: 'Bhavanisagar', dt: 'Erode'},
    {id: 108, name: 'Udhagamandalam', dt: 'Nilgiris'},
    {id: 109, name: 'Coonoor', dt: 'Nilgiris'},
    {id: 110, name: 'Gudalur', dt: 'Nilgiris'},
    {id: 111, name: 'Mettupalayam', dt: 'Coimbatore'},
    {id: 112, name: 'Avanashi', dt: 'Tiruppur'},
    {id: 113, name: 'Tiruppur North', dt: 'Tiruppur'},
    {id: 114, name: 'Tiruppur South', dt: 'Tiruppur'},
    {id: 115, name: 'Palladam', dt: 'Tiruppur'},
    {id: 116, name: 'Sulur', dt: 'Coimbatore'},
    {id: 117, name: 'Kavundampalayam', dt: 'Coimbatore'},
    {id: 118, name: 'Coimbatore North', dt: 'Coimbatore'},
    {id: 119, name: 'Thondamuthur', dt: 'Coimbatore'},
    {id: 120, name: 'Coimbatore South', dt: 'Coimbatore'},
    {id: 121, name: 'Singanallur', dt: 'Coimbatore'},
    {id: 122, name: 'Kinathukadavu', dt: 'Coimbatore'},
    {id: 123, name: 'Pollachi', dt: 'Coimbatore'},
    {id: 124, name: 'Valparai', dt: 'Coimbatore'},
    {id: 125, name: 'Udumalaipettai', dt: 'Tiruppur'},
    {id: 126, name: 'Madathukulam', dt: 'Tiruppur'},
    {id: 127, name: 'Palani', dt: 'Dindigul'},
    {id: 128, name: 'Oddanchatram', dt: 'Dindigul'},
    {id: 129, name: 'Athoor', dt: 'Dindigul'},
    {id: 130, name: 'Nilakottai', dt: 'Dindigul'},
    {id: 131, name: 'Natham', dt: 'Dindigul'},
    {id: 132, name: 'Dindigul', dt: 'Dindigul'},
    {id: 133, name: 'Vedasandur', dt: 'Dindigul'},
    {id: 134, name: 'Aravakurichi', dt: 'Karur'},
    {id: 135, name: 'Karur', dt: 'Karur'},
    {id: 136, name: 'Krishnarayapuram', dt: 'Karur'},
    {id: 137, name: 'Kulithalai', dt: 'Karur'},
    {id: 138, name: 'Manapaarai', dt: 'Tiruchirappalli'},
    {id: 139, name: 'Srirangam', dt: 'Tiruchirappalli'},
    {id: 140, name: 'Tiruchirappalli (West)', dt: 'Tiruchirappalli'},
    {id: 141, name: 'Tiruchirappalli (East)', dt: 'Tiruchirappalli'},
    {id: 142, name: 'Thiruverumbur', dt: 'Tiruchirappalli'},
    {id: 143, name: 'Lalgudi', dt: 'Tiruchirappalli'},
    {id: 144, name: 'Manachanallur', dt: 'Tiruchirappalli'},
    {id: 145, name: 'Musiri', dt: 'Tiruchirappalli'},
    {id: 146, name: 'Thuraiyur', dt: 'Tiruchirappalli'},
    {id: 147, name: 'Perambalur', dt: 'Perambalur'},
    {id: 148, name: 'Kunnam', dt: 'Perambalur'},
    {id: 149, name: 'Ariyalur', dt: 'Ariyalur'},
    {id: 150, name: 'Jayankondam', dt: 'Ariyalur'},
    {id: 151, name: 'Tittakudi', dt: 'Cuddalore'},
    {id: 152, name: 'Vriddhachalam', dt: 'Cuddalore'},
    {id: 153, name: 'Neyveli', dt: 'Cuddalore'},
    {id: 154, name: 'Panruti', dt: 'Cuddalore'},
    {id: 155, name: 'Cuddalore', dt: 'Cuddalore'},
    {id: 156, name: 'Kurinjipadi', dt: 'Cuddalore'},
    {id: 157, name: 'Bhuvanagiri', dt: 'Cuddalore'},
    {id: 158, name: 'Chidambaram', dt: 'Cuddalore'},
    {id: 159, name: 'Kattumannarkoil', dt: 'Cuddalore'},
    {id: 160, name: 'Sirkazhi', dt: 'Mayiladuthurai'},
    {id: 161, name: 'Mayiladuthurai', dt: 'Mayiladuthurai'},
    {id: 162, name: 'Poompuhar', dt: 'Mayiladuthurai'},
    {id: 163, name: 'Nagapattinam', dt: 'Nagapattinam'},
    {id: 164, name: 'Kilvelur', dt: 'Nagapattinam'},
    {id: 165, name: 'Vedaranyam', dt: 'Nagapattinam'},
    {id: 166, name: 'Thiruthuraipoondi', dt: 'Tiruvarur'},
    {id: 167, name: 'Mannargudi', dt: 'Tiruvarur'},
    {id: 168, name: 'Thiruvarur', dt: 'Tiruvarur'},
    {id: 169, name: 'Nannilam', dt: 'Tiruvarur'},
    {id: 170, name: 'Thiruvidaimarudur', dt: 'Thanjavur'},
    {id: 171, name: 'Kumbakonam', dt: 'Thanjavur'},
    {id: 172, name: 'Papanasam', dt: 'Thanjavur'},
    {id: 173, name: 'Thiruvaiyaru', dt: 'Thanjavur'},
    {id: 174, name: 'Thanjavur', dt: 'Thanjavur'},
    {id: 175, name: 'Orathanadu', dt: 'Thanjavur'},
    {id: 176, name: 'Pattukkottai', dt: 'Thanjavur'},
    {id: 177, name: 'Peravurani', dt: 'Thanjavur'},
    {id: 178, name: 'Gandharvakottai', dt: 'Pudukottai'},
    {id: 179, name: 'Viralimalai', dt: 'Pudukottai'},
    {id: 180, name: 'Pudukkottai', dt: 'Pudukottai'},
    {id: 181, name: 'Thirumayam', dt: 'Pudukottai'},
    {id: 182, name: 'Alangudi', dt: 'Pudukottai'},
    {id: 183, name: 'Aranthangi', dt: 'Pudukottai'},
    {id: 184, name: 'Karaikudi', dt: 'Sivaganga'},
    {id: 185, name: 'Tiruppattur', dt: 'Sivaganga'},
    {id: 186, name: 'Sivaganga', dt: 'Sivaganga'},
    {id: 187, name: 'Manamadurai', dt: 'Sivaganga'},
    {id: 188, name: 'Melur', dt: 'Madurai'},
    {id: 189, name: 'Madurai East', dt: 'Madurai'},
    {id: 190, name: 'Sholavandan', dt: 'Madurai'},
    {id: 191, name: 'Madurai North', dt: 'Madurai'},
    {id: 192, name: 'Madurai South', dt: 'Madurai'},
    {id: 193, name: 'Madurai Central', dt: 'Madurai'},
    {id: 194, name: 'Madurai West', dt: 'Madurai'},
    {id: 195, name: 'Thiruparankundram', dt: 'Madurai'},
    {id: 196, name: 'Tirumangalam', dt: 'Madurai'},
    {id: 197, name: 'Usilampatti', dt: 'Madurai'},
    {id: 198, name: 'Andipatti', dt: 'Theni'},
    {id: 199, name: 'Periyakulam', dt: 'Theni'},
    {id: 200, name: 'Bodinayakanur', dt: 'Theni'},
    {id: 201, name: 'Cumbum', dt: 'Theni'},
    {id: 202, name: 'Rajapalayam', dt: 'Virudhunagar'},
    {id: 203, name: 'Srivilliputhur', dt: 'Virudhunagar'},
    {id: 204, name: 'Sattur', dt: 'Virudhunagar'},
    {id: 205, name: 'Sivakasi', dt: 'Virudhunagar'},
    {id: 206, name: 'Virudhunagar', dt: 'Virudhunagar'},
    {id: 207, name: 'Aruppukkottai', dt: 'Virudhunagar'},
    {id: 208, name: 'Tiruchuli', dt: 'Virudhunagar'},
    {id: 209, name: 'Paramakudi', dt: 'Ramanathapuram'},
    {id: 210, name: 'Tiruvadanai', dt: 'Ramanathapuram'},
    {id: 211, name: 'Ramanathapuram', dt: 'Ramanathapuram'},
    {id: 212, name: 'Mudhukulathur', dt: 'Ramanathapuram'},
    {id: 213, name: 'Vilathikulam', dt: 'Thoothukudi'},
    {id: 214, name: 'Thoothukudi', dt: 'Thoothukudi'},
    {id: 215, name: 'Tiruchendur', dt: 'Thoothukudi'},
    {id: 216, name: 'Srivaikuntam', dt: 'Thoothukudi'},
    {id: 217, name: 'Ottapidaram', dt: 'Thoothukudi'},
    {id: 218, name: 'Kovilpatti', dt: 'Thoothukudi'},
    {id: 219, name: 'Sankarankovil', dt: 'Tenkasi'},
    {id: 220, name: 'Vasudevanallur', dt: 'Tenkasi'},
    {id: 221, name: 'Kadayanallur', dt: 'Tenkasi'},
    {id: 222, name: 'Tenkasi', dt: 'Tenkasi'},
    {id: 223, name: 'Alangulam', dt: 'Tenkasi'},
    {id: 224, name: 'Tirunelveli', dt: 'Tirunelveli'},
    {id: 225, name: 'Ambasamudram', dt: 'Tirunelveli'},
    {id: 226, name: 'Palayamkottai', dt: 'Tirunelveli'},
    {id: 227, name: 'Nanguneri', dt: 'Tirunelveli'},
    {id: 228, name: 'Radhapuram', dt: 'Tirunelveli'},
    {id: 229, name: 'Kanniyakumari', dt: 'Kanniyakumari'},
    {id: 230, name: 'Nagercoil', dt: 'Kanniyakumari'},
    {id: 231, name: 'Colachel', dt: 'Kanniyakumari'},
    {id: 232, name: 'Padmanabhapuram', dt: 'Kanniyakumari'},
    {id: 233, name: 'Vilavancode', dt: 'Kanniyakumari'},
    {id: 234, name: 'Killiyoor', dt: 'Kanniyakumari'},
  ],
  parties: [
    {
      id: 'p1',
      name: 'Dravida Munnetra Kazhagam2',
      leader: 1,
      alliance: 'dmk',
      comments: 10,
      symbol:
        'https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/Indian_Election_Symbol_Rising_Sun.png/75px-Indian_Election_Symbol_Rising_Sun.png',
    },
    {
      id: 'p2',
      name: 'Indian National Congress',
      leader: 2,
      alliance: 'dmk',
      symbol:
        'https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/Indian_National_Congress_symbol.svg/75px-Indian_National_Congress_symbol.svg.png',
    },
    {
      id: 'p3',
      name: 'Communist Party of India',
      leader: 3,
      alliance: 'dmk',
      symbol:
        'https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Indian_Election_Symbol_Ears_of_Corn_and_Sickle.png/75px-Indian_Election_Symbol_Ears_of_Corn_and_Sickle.png',
    },
    {
      id: 'p4',
      name: 'Communist Party of India (Marxist)',
      leader: 4,
      alliance: 'dmk',
      symbol:
        'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Indian_Election_Symbol_Hammer_Sickle_and_Star.png/75px-Indian_Election_Symbol_Hammer_Sickle_and_Star.png',
    },
    {
      id: 'p5',
      name: 'Viduthalai Chiruthaigal Katchi',
      leader: 5,
      alliance: 'dmk',
      symbol: '',
    },
    {
      id: 'p6',
      name: 'Indian Union Muslim League',
      leader: 6,
      alliance: 'dmk',
      symbol:
        'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Indian_Election_Symbol_Lader.svg/75px-Indian_Election_Symbol_Lader.svg.png',
    },
    {
      id: 'p7',
      name: 'Kongunadu Makkal Desia Katchi',
      leader: 7,
      alliance: 'dmk',
      symbol: '',
    },
    {
      id: 'p8',
      name: 'Marumalarchi Dravida Munnetra Kazhagam',
      leader: 8,
      alliance: 'dmk',
      symbol:
        'https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Indian_Election_Symbol_Top.png/75px-Indian_Election_Symbol_Top.png',
    },
    {
      id: 'p9',
      name: 'Tamizhaga Vazhvurimai Katchi',
      leader: 9,
      alliance: 'dmk',
      symbol: '',
    },
    {
      id: 'p10',
      name: 'Manithaneya Makkal Katchi',
      leader: 10,
      alliance: 'dmk',
      symbol: '',
    },
    {
      id: 'p11',
      name: 'All India Anna Dravida Munnetra Kazhagam',
      leader: 11,
      alliance: 'admk',
      symbol:
        'https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/AIADMK_Two_Leaves.png/90px-AIADMK_Two_Leaves.png',
    },
    {
      id: 'p12',
      name: 'Bharatiya Janata Party',
      leader: 12,
      alliance: 'admk',
      symbol:
        'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/BJP_election_symbol.png/75px-BJP_election_symbol.png',
    },
    {
      id: 'p13',
      name: 'Pattali Makkal Katchi',
      leader: 13,
      alliance: 'admk',
      symbol:
        'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Indian_Election_Symbol_Mango.png/75px-Indian_Election_Symbol_Mango.png',
    },
    {
      id: 'p14',
      name: 'Desiya Murpokku Dravida Kazhagam',
      leader: 14,
      alliance: 'admk',
      symbol:
        'https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Indian_Election_Symbol_Nagara.svg/75px-Indian_Election_Symbol_Nagara.svg.png',
    },
    {
      id: 'p15',
      name: 'Tamil Maanila Congress',
      leader: 15,
      alliance: 'admk',
      symbol:
        'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b2/Indian_Election_Symbol_Cycle.png/75px-Indian_Election_Symbol_Cycle.png',
    },
    {
      id: 'p16',
      name: 'Tamil Nadu Kongu Ilaingar Peravai',
      leader: 16,
      alliance: 'admk',
      symbol: '',
    },
    {
      id: 'p17',
      name: 'Mukkulathor Pulipadai',
      leader: 17,
      alliance: 'admk',
      symbol: '',
    },
    {
      id: 'p18',
      name: 'Puthiya Tamilagam',
      leader: 18,
      alliance: 'admk',
      symbol: '',
    },
    {
      id: 'p19',
      name: 'Puthiya Needhi Katchi',
      leader: 19,
      alliance: 'admk',
      symbol: '',
    },
    {
      id: 'p20',
      name: 'Naam Tamilar Katchi',
      leader: 20,
      symbol:
        'https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Indian_Election_Symbol_sugarcane_farmer.svg/120px-Indian_Election_Symbol_sugarcane_farmer.svg.png',
    },
    {
      id: 'p21',
      name: 'Amma Makkal Munnettra Kazagam',
      leader: 21,
      symbol:
        'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Pressure_Cooker_symbol.png/90px-Pressure_Cooker_symbol.png',
    },
    {
      id: 'p22',
      name: 'Makkal Needhi Maiam',
      leader: 22,
      alliance: 'mnm',
      symbol:
        'https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Indian_Election_Symbol_Battery-Torch.png/90px-Indian_Election_Symbol_Battery-Torch.png',
    },
    {
      id: 'p23',
      name: 'All India Samathuva Makkal Katchi',
      leader: 23,
      alliance: 'mnm',
      symbol: '',
    },
    {
      id: 'p24',
      name: 'Indhiya Jananayaga Katchi',
      leader: 24,
      symbol: '',
    },
  ],
  candidates: [
    {id: 1, name: 'M. K. Stalin', party: 'p1', constituency: -1},
    {id: 2, name: 'K. S. Alagiri', party: "p2", constituency: -1},
    {id: 3, name: 'R. Mutharasan', party: "p3", constituency: -1},
    {id: 4, name: 'K. Balakrishnan', party: "p4", constituency: -1},
    {id: 5, name: 'Thol. Thirumavalavan', party: "p5", constituency: -1},
    {id: 6, name: 'K. M. Kader Mohideen', party: "p6", constituency: -1},
    {id: 7, name: 'E. R. Eswaran', party: "p7", constituency: -1},
    {id: 8, name: 'Vaiko', party: "p8", constituency: -1},
    {id: 9, name: 'T. Velmurugan', party: "p9", constituency: -1},
    {id: 10, name: 'M. H. Jawahirullah', party: "p10", constituency: -1},
    {id: 11, name: 'Edappadi K. Palaniswami', party: "p11", constituency: -1},
    {id: 12, name: 'L. Murugan', party: "p12", constituency: -1},
    {id: 13, name: 'S. Ramadoss', party: "p13", constituency: -1},
    {id: 14, name: 'Vijayakanth', party: "p14", constituency: -1},
    {id: 15, name: 'G. K. Vasan', party: "p15", constituency: -1},
    {id: 16, name: 'U. Thaniyarasu', party: "p16", constituency: -1},
    {id: 17, name: 'Karunas', party: "p17", constituency: -1},
    {id: 18, name: 'K. Krishnasamy', party: "p18", constituency: -1},
    {id: 19, name: 'A. C. Shanmugam', party: "p19", constituency: -1},
    {id: 20, name: 'Seeman', party: "p20", constituency: -1},
    {id: 21, name: 'T. T. V. Dhinakaran', party: "p21", constituency: -1},
    {id: 22, name: 'Kamal Haasan', party: "p22", constituency: -1},
    {id: 23, name: 'R. Sarathkumar', party: "p23", constituency: -1},
    {id: 24, name: 'T. R. Paarivendhar', party: "p24", constituency: -1},
    {id: -1, name: '', party: -1, constituency: -1},
    {id: -1, name: '', party: -1, constituency: -1},
    {id: -1, name: '', party: -1, constituency: -1},
    {id: -1, name: '', party: -1, constituency: -1},
    {id: -1, name: '', party: -1, constituency: -1},
    {id: -1, name: '', party: -1, constituency: -1},
    {id: -1, name: '', party: -1, constituency: -1},
    {id: -1, name: '', party: -1, constituency: -1},
    {id: -1, name: '', party: -1, constituency: -1},
    {id: -1, name: '', party: -1, constituency: -1},
    {id: -1, name: '', party: -1, constituency: -1},
    {id: -1, name: '', party: -1, constituency: -1},
    {id: -1, name: '', party: -1, constituency: -1},
    {id: -1, name: '', party: -1, constituency: -1},
    {id: -1, name: '', party: -1, constituency: -1},
    {id: -1, name: '', party: -1, constituency: -1},
    {id: -1, name: '', party: -1, constituency: -1},
    {id: -1, name: '', party: -1, constituency: -1},
    {id: -1, name: '', party: -1, constituency: -1},
  ],
};
